// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  afbeelding_met_tekst: dynamic(() => import("./AfbeeldingMetTekst")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  navigatie_item: dynamic(() => import("./NavigatieItem")),
  paragraaf: dynamic(() => import("./Paragraaf")),
  quote: dynamic(() => import("./Quote")),
};
